const OpenAI = require("openai");
const Busboy = require("busboy");
const { handleUpload } = require("@vercel/blob/client");
const { download } = require("@vercel/blob");

const client = new OpenAI({ apiKey: process.env.ASK || process.env.OPENAI_API_KEY });
const VECTOR_STORE_ID = process.env.OPENAI_VECTOR_STORE_ID;

function send(res,status,body){
  res.status(status).setHeader("Content-Type","application/json; charset=utf-8");
  res.end(JSON.stringify(body));
}
function route(req){
  const p=new URL(req.url,`https://${req.headers.host||"localhost"}`).pathname.replace(/\/+$/,"");
  if(p.endsWith("/ask")) return "ask";
  if(p.endsWith("/rewrite")) return "rewrite";
  if(p.endsWith("/context-upload-token")) return "context-upload-token";
  if(p.endsWith("/context-upload")) return "context-upload";
  if(p.endsWith("/context-search")) return "context-search";
  return "";
}
async function jsonBody(req){
  if(req.body&&typeof req.body==="object") return req.body;
  let raw=""; for await(const c of req) raw+=c;
  return raw?JSON.parse(raw):{};
}
function textOf(r){
  if(!r)return"";
  if(typeof r.output_text==="string")return r.output_text;
  if(Array.isArray(r.output))return r.output.flatMap(x=>Array.isArray(x.content)?x.content:[]).map(x=>x.text||"").filter(Boolean).join("\n");
  return r.text||"";
}
async function ask(req,res){
  if(req.method!=="POST")return send(res,405,{error:"Method not allowed"});
  const b=await jsonBody(req),q=String(b.question||"").trim();
  if(!q)return send(res,400,{error:"question fehlt"});
  const r=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:q});
  return send(res,200,{result:textOf(r),output_text:r.output_text||textOf(r)});
}
async function rewrite(req,res){return ask(req,res);}

/*
 * Vercel Blob client-upload token endpoint.
 * The browser uploads directly to Blob; the original file does not pass
 * through the Vercel Function payload.
 */
async function contextUploadToken(req,res){
  if(req.method!=="POST")return send(res,405,{error:"Method not allowed"});
  if(!process.env.BLOB_READ_WRITE_TOKEN)return send(res,500,{error:"BLOB_READ_WRITE_TOKEN fehlt"});
  try{
    // Important: handleUpload expects the JSON body generated by @vercel/blob/client.
    // Do not disable JSON body parsing for this route.
    const body=await jsonBody(req);
    const result=await handleUpload({
      token:process.env.BLOB_READ_WRITE_TOKEN,
      body,
      request:req,
      onBeforeGenerateToken:async(pathname,clientPayload,multipart)=>{
        let payload={};
        try{payload=clientPayload?JSON.parse(clientPayload):{}}catch{}
        const allowed=[
          "application/pdf",
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "application/vnd.ms-powerpoint",
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "text/plain","text/markdown","text/csv"
        ];
        return {
          allowedContentTypes:allowed,
          maximumSizeInBytes:100*1024*1024,
          tokenPayload:JSON.stringify({
            context_id:String(payload.context_id||""),
            metadata:payload.metadata||{}
          })
        };
      },
      onUploadCompleted:async({blob,tokenPayload})=>{
        console.log("SprachKi Blob upload completed",blob.pathname,tokenPayload);
      }
    });
    return send(res,200,result);
  }catch(e){
    console.error("context-upload-token",e);
    return send(res,400,{error:e.message||"Blob-Upload konnte nicht vorbereitet werden."});
  }
}

/*
 * Small JSON request after the direct Blob upload.
 * It downloads the Blob server-side and sends it to OpenAI.
 */
async function contextUpload(req,res){
  if(req.method!=="POST")return send(res,405,{error:"Method not allowed"});
  if(!VECTOR_STORE_ID)return send(res,500,{error:"OPENAI_VECTOR_STORE_ID fehlt"});
  const b=await jsonBody(req);
  const url=String(b.blob_url||"").trim();
  const contextId=String(b.context_id||"").trim();
  const name=String(b.name||b.pathname||"Quelle").trim();
  if(!url)return send(res,400,{error:"blob_url fehlt"});
  if(!contextId)return send(res,400,{error:"context_id fehlt"});

  try{
    const downloaded=await download(url);
    const contentType=b.type||downloaded.contentType||"application/octet-stream";
    const response=downloaded.stream;

    // Node's File can be constructed from a Blob/stream only after collecting bytes.
    const chunks=[];
    for await(const chunk of response) chunks.push(Buffer.from(chunk));
    const buffer=Buffer.concat(chunks);

    const uploaded=await client.files.create({
      file:new File([buffer],name,{type:contentType}),
      purpose:"assistants"
    });

    const metadata=(b.metadata&&typeof b.metadata==="object")?b.metadata:{};
    const attrs={
      context_id:contextId,
      source_name:name,
      source_type:contentType,
      ...metadata
    };

    const vs=await client.vectorStores.files.create(VECTOR_STORE_ID,{
      file_id:uploaded.id,
      attributes:attrs
    });

    return send(res,200,{
      file_id:uploaded.id,
      name,
      type:contentType,
      indexed:vs.status==="completed",
      status:vs.status||"in_progress",
      vector_store_file_id:vs.id,
      blob_url:url
    });
  }catch(e){
    console.error("context-upload",e);
    return send(res,500,{error:e.message||"Datei konnte nicht in den Quellenindex übernommen werden."});
  }
}

async function contextSearch(req,res){
  if(req.method!=="POST")return send(res,405,{error:"Method not allowed"});
  if(!VECTOR_STORE_ID)return send(res,500,{error:"OPENAI_VECTOR_STORE_ID fehlt"});
  const b=await jsonBody(req),query=String(b.query||"").trim(),contextId=String(b.context_id||"").trim();
  if(!query)return send(res,400,{error:"query fehlt"});
  if(!contextId)return send(res,400,{error:"context_id fehlt"});

  const r=await client.vectorStores.search(VECTOR_STORE_ID,{
    query,max_num_results:8,rewrite_query:true,
    attribute_filter:{type:"eq",key:"context_id",value:contextId}
  });
  const chunks=[],counts={};
  for(const item of(r.data||[])){
    const text=(item.content||[]).map(x=>x.text||"").filter(Boolean).join("\n").trim();
    if(!text)continue;
    const name=item.filename||item.file_name||"Quelle";
    chunks.push({file_id:item.file_id,filename:name,score:item.score,text});
    counts[name]=(counts[name]||0)+1;
  }
  return send(res,200,{
    relevant_context:chunks.map((c,i)=>`[Quelle ${i+1}: ${c.filename} | Treffer ${Number(c.score||0).toFixed(3)}]\n${c.text}`).join("\n\n"),
    chunks,
    sources:Object.entries(counts).map(([name,hits])=>({name,hits}))
  });
}

module.exports=async function(req,res){
  try{
    switch(route(req)){
      case "ask":return ask(req,res);
      case "rewrite":return rewrite(req,res);
      case "context-upload-token":return contextUploadToken(req,res);
      case "context-upload":return contextUpload(req,res);
      case "context-search":return contextSearch(req,res);
      default:return send(res,404,{error:"Unbekannter API-Endpunkt"});
    }
  }catch(e){
    console.error(e);
    return send(res,500,{error:e.message||"Interner Serverfehler"});
  }
};
